### ISSUE TITLE
Updated Version with ESP32 Compatibility

### ISSUE THREAD

**Issue by TL00k** [hkiam/pool-heat-pump#2]
Any Plans for an ESP32-Compatible Version (ESPHome Would Be Awesome!) — and does this work without the original display?

**Comment by The-sultan** [comment]
I have created an ESP32/ESP8266 version of this and separated things in two layers: a library called pool-heater-core that has only the code for interacting with the heat pump and a wrapper for ESPHome.
**Disclaimer: I have not tested the code on a ESP32, use it at your own risk.**

If you decide to use this, you just need to add this to your yaml on ESPHome:

```
external_components:
  - source: github://The-sultan/pool-heater-esphome
    components: [ pool_heater ]
pool_heater:
  id: my_pool_heater
climate:
  - platform: pool_heater
    pool_heater_id: my_pool_heater
    name: "Pool Heater Thermostat"
```

Core component: https://github.com/The-sultan/pool-heater-core
ESPHome wrapper: https://github.com/The-sultan/pool-heater-esphome
